[package]
name = "hoconvert"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "3.0.0-beta.5", features = ["yaml", "suggestions"] }
clap_generate = "3.0.0-beta.5"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
hocon = "0.5.2"
predicates = "2.0.3"
assert_cmd = "2.0.2"
