[package]
name = "hoconvert"
version = "0.1.3"
authors = ["Mathias Oertel <mathias.oertel@pm.me>"]
edition = "2021"
description = "CLI tool to convert HOCON into valid JSON or YAML."
readme = "README.md"
keywords = ["cli", "hocon", "json", "yaml", "converter"]
categories = ["command-line-utilities"]
license = "MIT"
repository = "https://github.com/maoertel/hoconvert"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
clap_generate = "3.0.3"

hocon = "0.9.0"

serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"

[dev-dependencies]
predicates = "2.1.1"
assert_cmd = "2.0.4"
